---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud에서는 여러 Cloud Volumes ONTAP 구성이 지원됩니다. 
---
= Google Cloud에서 Cloud Volumes ONTAP에 대해 지원되는 구성입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud에서는 여러 Cloud Volumes ONTAP 구성이 지원됩니다.



== 라이센스에 의해 지원되는 구성

Cloud Volumes ONTAP는 Google Cloud에서 단일 노드 시스템으로, 내결함성 및 무중단 운영을 위한 고가용성(HA) 노드 쌍으로 사용할 수 있습니다.

단일 노드 시스템을 HA 쌍으로 업그레이드하는 것은 지원되지 않습니다. 단일 노드 시스템과 HA 쌍 간에 전환하려면 새 시스템을 구축하고 기존 시스템의 데이터를 새 시스템으로 복제해야 합니다.

Cloud Volumes ONTAP는 클라우드 공급자의 예약된 VM 인스턴스 또는 주문형 VM 인스턴스에서 실행될 수 있습니다. 다른 VM 인스턴스 유형을 사용하는 솔루션은 지원되지 않습니다.

[role="tabbed-block"]
====
.용량 기반 라이센스
--
[cols="h,d,d,d"]
|===
|  | 프리모늄 | 최적화된 ^4^ | 용량 기반 라이센스(Essentials 및 Professional) 


| 최대 시스템 용량(디스크 + 오브젝트 스토리지) | 500GiB  a| 
용량 기반 라이선싱을 통해 각 Cloud Volumes ONTAP 시스템은 개체 스토리지에 대한 계층화를 지원합니다.  전체 계층형 용량은 클라우드 제공자의 버킷 한도까지 확장될 수 있습니다.  라이센스에는 용량 제한이 부과되지 않지만 다음을 따라야 합니다. https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^] 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장합니다.



| 지원되는 시스템 유형 ^1^  a| 
* N1 - 표준 - 8(1)
* N1 - 표준 - 32 - 1
* N2-표준-4
* N2 - 표준 - 8
* N2-표준-16
* N2-표준-32
* N2-표준-48
* N2-표준-64

 a| 
* N2-표준-4
* N2 - 표준 - 8

 a| 
* N1 - 표준 - 8(1)
* N1 - 표준 - 32 - 1
* N2-표준-4
* N2 - 표준 - 8
* N2-표준-16
* N2-표준-32
* N2-표준-48
* N2-표준-64




| 지원되는 디스크 유형 ^2^ 3+| 균형 잡힌 영구 디스크 3, 성능(SSD) 영구 디스크 및 표준(HDD) 영구 디스크. 
|===
참고:

. ^1^ Google Cloud에서 Cloud Volumes ONTAP 의 새 인스턴스를 배포할 때 NetApp 콘솔에서 n1 시리즈 머신을 더 이상 선택할 수 없습니다. n1 시리즈 머신은 기존의 오래된 시스템에서만 유지 및 지원됩니다. Cloud Volumes ONTAP 의 새로운 배포는 Google Cloud 9.8 릴리스부터만 지원됩니다. Cloud Volumes ONTAP 9.8 이상과 호환되는 n2 시리즈 머신으로 전환하는 것이 좋습니다. 하지만 n1 시리즈 머신은 API를 통해 이루어진 새로운 배포에 사용할 수 있습니다.
+
CUSTOM-4-16384 시스템 유형은 새로운 Cloud Volumes ONTAP 시스템에서 더 이상 지원되지 않습니다. 이 기계 유형에서 실행 중인 기존 시스템이 있는 경우 계속 사용할 수 있지만 n2-standard-4 기계 유형으로 전환하는 것이 좋습니다.

. 디스크 제한을 사용하면 디스크만 사용하여 최대 시스템 용량 제한에 도달하지 못할 수 있습니다. 용량 제한은 에 따라 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]도달할 수 있습니다.
+
link:reference-limits-gcp.html["Google Cloud의 디스크 제한에 대해 자세히 알아보십시오"].

. 향상된 쓰기 성능은 균형 있는 영구 디스크와 성능(SSD) 영구 디스크를 사용할 때 활성화됩니다.
+
Cloud Volumes ONTAP 9.13.0, _Flash Cache_, 빠른 쓰기 속도 및 8,896바이트의 더 높은 MTU(최대 전송 단위)부터 다음 HA 쌍 배포 인스턴스에 사용할 수 있습니다.

+
** N2-표준-16
** N2-표준-32
** N2-표준-48
** N2-표준-64
+
적합한 인스턴스 유형을 구축할 때 _Flash Cache_ 및 고속 쓰기 속도를 설정할 수 있습니다. 8,896바이트의 더 높은 최대 전송 단위를 사용하려면 구축을 위해 VPC-1, VPC-2 또는 VPC-3을 선택해야 합니다. MTU가 높을수록 네트워크 처리량이 증가합니다. 이러한 배포 중 하나를 시작하는 방법에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud에서 HA 쌍 시작"].

+

NOTE: _Flash Cache_, 높은 쓰기 모드 및 8,896의 MTU는 기능별로 다르며 구성된 인스턴스 내에서 개별적으로 비활성화할 수 없습니다.



. ^4^ 2025년 8월 11일부터 Cloud Volumes ONTAP Optimized 라이선스는 더 이상 사용되지 않으며 Google Cloud 마켓플레이스에서 PAYGO(Pay-as-you-go) 구독을 구매하거나 갱신할 수 없습니다.  자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP의 새로운 기능"^] .


--
.노드 기반 라이센스
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO 탐색 | PAYGO 표준 | PAYGO 프리미엄 | 노드 기반 BYOL 


| 최대 시스템 용량(디스크 + 오브젝트 스토리지) | 2TB^2^ | 10TiB | 368TiB | 라이센스당 368TiB입니다 


| 지원되는 시스템 유형 ^3^  a| 
* N2-표준-4

 a| 
* N1 - 표준 - 8 - 3
* N2 - 표준 - 8

 a| 
* N1 - 표준 - 32 - 3
* N2-표준-16
* N2-표준-32
* N2-표준-48
* N2-표준-64

 a| 
* N1 - 표준 - 8 - 3
* N1 - 표준 - 32 - 3
* N2-표준-4
* N2 - 표준 - 8
* N2-표준-16
* N2-표준-32
* N2-표준-48
* N2-표준-64




| 지원되는 디스크 유형입니다 4+| 균형 잡힌 영구 디스크^4^, 성능(SSD) 영구 디스크^4^, 표준(HDD) 영구 디스크. 
|===
참고:

. 디스크 제한을 사용하면 디스크만 사용하여 최대 시스템 용량 제한에 도달하지 못할 수 있습니다. 용량 제한은 에 따라 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]도달할 수 있습니다.
+
link:reference-limits-gcp.html["Google Cloud의 디스크 제한에 대해 자세히 알아보십시오"].

. Google 클라우드 스토리지로의 데이터 계층화는 PAYGO Explore에서 지원되지 않습니다.
. ^3^ Google Cloud에서 Cloud Volumes ONTAP 의 새 인스턴스를 배포할 때 콘솔에서 n1 시리즈 머신을 더 이상 선택할 수 없습니다. n1 시리즈 머신은 기존의 오래된 시스템에서만 유지 및 지원됩니다. Cloud Volumes ONTAP 의 새로운 배포는 Google Cloud 9.8 릴리스부터만 지원됩니다. Cloud Volumes ONTAP 9.8 이상과 호환되는 n2 시리즈 머신으로 전환하는 것이 좋습니다. 하지만 n1 시리즈 머신은 API를 통해 수행되는 새로운 배포에 사용할 수 있습니다.
+
CUSTOM-4-16384 시스템 유형은 새로운 Cloud Volumes ONTAP 시스템에서 더 이상 지원되지 않습니다. 이 기계 유형에서 실행 중인 기존 시스템이 있는 경우 계속 사용할 수 있지만 n2-standard-4 기계 유형으로 전환하는 것이 좋습니다.

. 향상된 쓰기 성능은 균형 있는 영구 디스크와 성능(SSD) 영구 디스크를 사용할 때 활성화됩니다.


콘솔은 Standard 및 BYOL에 대해 지원되는 추가 머신 유형인 n1-highmem-4를 보여줍니다. 하지만 이 머신 유형은 프로덕션 환경에는 적합하지 않습니다. 특정 연구실 환경에서만 사용할 수 있도록 만들었습니다.

Cloud Volumes ONTAP 소프트웨어 버전 9.13.0,_Flash Cache_, 고속 쓰기 속도 및 8,896바이트의 더 높은 MTU(최대 전송 단위)를 사용하여 다음의 HA 쌍 구축 인스턴스를 사용할 수 있습니다.

* N2-표준-16
* N2-표준-32
* N2-표준-48
* N2-표준-64


적합한 인스턴스 유형을 구축할 때 _Flash Cache_ 및 고속 쓰기 속도를 설정할 수 있습니다. 8,896바이트의 더 높은 최대 전송 단위를 사용하려면 구축을 위해 VPC-1, VPC-2 또는 VPC-3을 선택해야 합니다. MTU가 높을수록 네트워크 처리량이 증가합니다. 이러한 배포 중 하나를 시작하는 방법에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud에서 HA 쌍 시작"].


NOTE: _Flash Cache_, 높은 쓰기 모드 및 8,896의 MTU는 기능별로 다르며 구성된 인스턴스 내에서 개별적으로 비활성화할 수 없습니다.

--
====
특정 머신 유형에 대한 자세한 내용은 Google Cloud 문서를 참조하세요.

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1 시리즈 일반용 기계 유형"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2 시리즈 일반용 기계 유형"^]




== 지원되는 디스크 크기입니다

Google Cloud에서는 aggregate에 동일한 유형과 크기의 디스크를 최대 6개까지 포함할 수 있습니다. 지원되는 디스크 크기는 다음과 같습니다.

* 100GB
* 500GB
* 1TB
* 2TB입니다
* 4TB
* 8TB
* 16TB
* 64TB




== 지원 지역

Google Cloud 지역 지원은 을 참조하십시오 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes 글로벌 지역"^].
