---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support 
summary: 이 페이지에서는 NetApp이 클라우드 공급자와 협력하여 이슈 발생 시 이를 해결하는 방법에 대해 설명합니다. 
---
= 클라우드 공급자 통합
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 페이지에서는 NetApp이 클라우드 공급자와 협력하여 이슈 발생 시 이를 해결하는 방법에 대해 설명합니다.



== 협력 지원 모범 사례

NetApp은 정식 사용자에게 지원을 제공할 것을 약속하며 정식 사용자가 Cloud Volumes ONTAP에 기술 지원 문제를 보고할 때 상업적으로 합당한 노력을 기울입니다. NetApp과 해당 클라우드 공급자는 상호 라이센스가 부여된 소프트웨어 또는 인프라에 대한 직접적인 지원 의무를 지지 않습니다.

NetApp은 적용 가능한 클라우드 공급자 서비스의 결과일 수 있는 고객 기술 문제에 대해 해당 클라우드 공급자와 연결할 수 있는 툴을 구축했습니다. 그러나 원활한 지원 흐름을 유지하는 가장 좋은 방법은 (i) NetApp 및 해당 클라우드 공급자와 현재 지원 계약을 유지하고 (ii) 기술 문제가 발생하거나 고객이 분명한 설명을 요구하는 경우 NetApp 및 해당 클라우드 제공업체와 공동 에스컬레이션 회의를 조정하는 것입니다 어떤 제품 또는 서비스가 이러한 기술적 문제를 야기하고 있는지 확인합니다.



== Azure 유지 관리 이벤트입니다

Microsoft는 Cloud Volumes ONTAP VM에 영향을 줄 수 있는 Azure VM(가상 머신) 인프라의 유지보수 이벤트를 예약하고 프로그래밍 방식으로 알립니다. 이러한 이벤트는 유지 보수 기간 15분 전에 발표됩니다.

Cloud Volumes ONTAP HA(고가용성) 쌍에서는 유지 관리 이벤트에 대한 특별한 처리가 지원됩니다. 애플리케이션 상태를 유지하기 위해 사전 예방 테이크오버 를 수행하여 안정성을 우선으로 결정합니다. 15초 이상의 연결이 끊어지면 페일오버 기능이 비활성화됩니다.

유지보수 윈도우가 공지되면 타겟 노드의 파트너 노드가 테이크오버 수행 유지 관리가 완료되면 반환이 시작됩니다. 반환 후 HA 쌍이 정상 상태로 돌아올 것으로 예상됩니다. 이렇게 하지 않으면 NetApp Support에 문의하십시오. 유지보수 이벤트는 한 번에 HA 쌍 내의 VM 중 하나를 대상으로 하며, 일반적으로 두 노드는 비교적 짧은 기간 동안 타겟으로 합니다.

Cloud Volumes ONTAP에서 지속적으로 사용할 수 없는 CIFS 공유를 사용하는 CIFS/SMB 클라이언트는 인수 발생 시, 그리고 세션에서 사용하는 aggregate가 다시 애그리게이트의 홈 노드로 제공되면 모두 세션이 손실됩니다. 이는 CIFS/SMB 프로토콜 자체에 의해 적용되는 제한 사항입니다. 고객은 Takeover 및 Giveback에서 발생할 수 있는 문제를 방지하기 위해 타사 제품을 사용할 수 있습니다. 자세한 내용은 NetApp Support에 문의하십시오.
