---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.18.1에는 새로운 기능 향상이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.18.1의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이제 Cloud Volumes ONTAP 9.18.1을 배포 및 업그레이드할 수 있습니다. NetApp Console에서 이번 릴리스의 기본 버전과 배포 및 업그레이드에 사용 가능한 최신 패치 버전을 확인할 수 있습니다.

최신 버전의 NetApp Console에 도입된 Cloud Volumes ONTAP 기능에 대해 알아보려면 새로운 기능 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^]을 참조하십시오.



== 9.18.1 GA(2026년 2월 10일)

Cloud Volumes ONTAP 9.18.1 General Availability 릴리스가 Amazon Web Services(AWS) 및 Microsoft Azure에서 배포 및 업그레이드할 수 있게 되었습니다. 이 버전은 Google Cloud에서 배포 및 업그레이드할 수 없습니다.



== 노트 업그레이드

이 릴리스 업그레이드에 대한 자세한 내용은 이 노트를 참조하십시오.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 콘솔에서 완료해야 합니다. System Manager나 CLI를 사용하여 Cloud Volumes ONTAP 업그레이드해서는 안 됩니다. 그렇게 하면 시스템 안정성에 영향을 미칠 수 있습니다.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["콘솔에서 알림을 받을 때 업그레이드하는 방법을 알아보세요."^] .



=== 지원되는 업그레이드 경로입니다

AWS 및 Azure에서 9.17.1 P1 이상 패치가 적용된 Cloud Volumes ONTAP을 9.18.1로 업그레이드할 수 있습니다. Console에서 업그레이드 대상 Cloud Volumes ONTAP 시스템을 이 릴리스로 업그레이드하라는 메시지가 표시됩니다.


NOTE: Google Cloud에서는 Cloud Volumes ONTAP 9.18.1로 업그레이드할 수 없습니다.



=== 알아 보십시오

* 단일 노드 시스템 업그레이드는 최대 25분 동안 시스템을 오프라인 상태로 전환하며, 이 시간 동안 I/O가 중단됩니다.
* HA 쌍 업그레이드는 무중단으로 수행되며 I/O가 중단되지 않습니다. 이러한 무중단 업그레이드 프로세스 중에는 각 노드가 동시에 업그레이드되어 클라이언트에 입출력을 계속 제공합니다.

