---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1에는 새로운 기능이 추가되었습니다. 
---
= Cloud Volumes ONTAP 9.17.1의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1은 Azure와 Google Cloud에서 배포 및 업그레이드할 수 있습니다.



== 9.17.1 RC1(2025년 9월 4일)

이제 Cloud Volumes ONTAP 9.17.1 릴리스 후보 1을 사용하여 Azure 및 Google Cloud에 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다.



== 노트 업그레이드

이 릴리스 업그레이드에 대한 자세한 내용은 이 노트를 참조하십시오.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 BlueXP에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXP에서 알림을 받을 때 업그레이드하는 방법에 대해 알아봅니다"^].



=== 지원되는 업그레이드 경로입니다

Azure 및 Google Cloud의 9.16.1 릴리스에서 Cloud Volumes ONTAP 9.17.1 RC1로 업그레이드할 수 있습니다.  BlueXP 적격 Cloud Volumes ONTAP 시스템을 이 릴리스로 업그레이드하라는 메시지를 표시합니다.


NOTE: AWS의 경우 이 업그레이드에 대한 메시지가 표시되지 않습니다.  AWS에서는 Cloud Volumes ONTAP 9.17.1 RC1로의 업그레이드가 지원되지 않습니다.



=== 알아 보십시오

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 쌍 업그레이드는 무중단으로 수행되며 I/O가 중단되지 않습니다. 이러한 무중단 업그레이드 프로세스 중에는 각 노드가 동시에 업그레이드되어 클라이언트에 입출력을 계속 제공합니다.

