---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP은 안정적인 운영을 제공하기 위해 Google Cloud에서 스토리지 구성 제한을 가지고 있습니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오. 
---
= Google Cloud의 스토리지 제한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP는 안정적인 운영을 제공하기 위해 스토리지 구성에 제한이 있습니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오.



== 라이센스별 최대 시스템 용량

Cloud Volumes ONTAP 시스템의 최대 시스템 용량은 라이센스에 따라 결정됩니다. 최대 시스템 용량에는 디스크 기반 스토리지와 데이터 계층화에 사용되는 오브젝트 스토리지가 포함됩니다.

NetApp은 시스템 용량 제한을 초과하지 않습니다. 라이센스가 부여된 용량 제한에 도달하면 Cloud Manager에서 작업 필요 메시지를 표시하고 더 이상 디스크를 추가할 수 없습니다.

일부 구성에서는 디스크 제한만으로 용량 제한에 도달하지 못합니다. 용량 제한에 도달할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. 자세한 내용은 아래의 디스크 제한을 참조하십시오.

[cols="25,75"]
|===
| 라이센스 | 최대 시스템 용량(디스크 + 오브젝트 스토리지) 


| 프리모늄 | 500GB 


| PAYGO 탐색 | 2TB(Explore에서 데이터 계층화가 지원되지 않음) 


| PAYGO 표준 | 10TB 


| PAYGO 프리미엄 | 368TB 


| 노드 기반 라이센스 | 라이센스당 368TB 


| 용량 기반 라이센스 | 2 PiB 
|===


===== HA 쌍의 경우, 노드당 또는 전체 HA 쌍의 라이센스 용량 제한이 있습니까?

용량 제한은 전체 HA 쌍에 대한 것입니다. 노드 단위로 표시되지 않습니다. 예를 들어, Premium 라이센스를 사용하는 경우 두 노드 간에 최대 368TB의 용량을 가질 수 있습니다.



===== HA 쌍의 경우, 미러링된 데이터가 라이센스 용량 제한에 대해 계산됩니까?

아니요, 그렇지 않습니다. HA 쌍의 데이터는 노드 간에 동기식으로 미러링되므로 Google Cloud에서 장애가 발생할 경우 데이터를 사용할 수 있습니다. 예를 들어, 노드 A에서 8TB 디스크를 구매하는 경우 Cloud Manager에서는 미러링된 데이터에 사용되는 노드 B에도 8TB 디스크를 할당합니다. 16TB의 용량을 프로비저닝했지만 라이센스 제한에 대해 8TB만 계산합니다.



== 디스크 및 계층화 제한

아래 표에는 디스크 단독으로, 디스크 및 콜드 데이터를 오브젝트 스토리지로 계층화하는 경우 최대 시스템 용량이 나와 있습니다. 디스크 제한은 사용자 데이터가 포함된 디스크에만 적용됩니다. 이 제한에는 부팅 디스크 및 루트 디스크가 포함되지 않습니다.

[cols="60,40"]
|===
| 매개 변수 | 제한 


| 최대 데이터 디스크 수  a| 
* 단일 노드 시스템용 124개
* HA 쌍에 대한 노드당 123개




| 최대 디스크 크기입니다 | 64TB 


| 디스크만 사용할 경우 최대 시스템 용량입니다 | 256TB^1^ 


| 디스크 및 콜드 데이터를 Google Cloud Storage 버킷으로 계층화하여 시스템 용량 극대화 | 라이센스에 따라 다릅니다. 위의 표를 참조하십시오. 
|===
^1^ 이 제한은 Google Cloud Platform의 가상 머신 제한값에 의해 정의됩니다.



== 애그리게이트 제한

Cloud Volumes ONTAP는 Google Cloud Platform 디스크를 _aggregate_로 그룹화합니다. Aggregate는 볼륨에 스토리지를 제공합니다.

[cols="2*"]
|===
| 매개 변수 | 제한 


| 최대 데이터 애그리게이트 수 ^1^  a| 
* 단일 노드의 경우 99입니다
* 전체 HA 쌍을 지원하는 64개




| 최대 애그리게이트 크기입니다 | 256TB의 물리적 용량^2^ 


| 애그리게이트당 디스크 수 | 1-6^3^ 


| 애그리게이트당 최대 RAID 그룹 수 | 1 
|===
참고:

. 최대 데이터 애그리게이트 수에는 루트 애그리게이트가 포함되지 않습니다.
. 애그리게이트 용량 한도는 애그리게이트를 구성하는 디스크를 기준으로 합니다. 이 제한에는 데이터 계층화에 사용되는 오브젝트 스토리지가 포함되지 않습니다.
. Aggregate의 모든 디스크는 동일한 크기여야 합니다.




== 스토리지 VM 제한

일부 구성을 사용하면 Cloud Volumes ONTAP용 SVM(스토리지 VM)을 추가로 생성할 수 있습니다.

이러한 제한은 테스트를 거친 것입니다. 이론적으로는 추가 스토리지 VM을 구성할 수 있지만 이는 지원되지 않습니다.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html["추가 스토리지 VM을 생성하는 방법을 알아보십시오"^].

[cols="2*"]
|===
| 사용권 유형 | 스토리지 VM 제한 


| * Freemium *  a| 
총 24개의 스토리지 VM ^1^



| * 용량 기반 PAYGO 또는 BYOL *^2^  a| 
총 24개의 스토리지 VM ^1^



| * 노드 기반 BYOL * ^3^  a| 
총 24개의 스토리지 VM ^1^



| * 노드 기반 PAYGO *  a| 
* 1 데이터 제공용 스토리지 VM
* 재해 복구용 스토리지 VM 1개


|===
. 이러한 24개의 스토리지 VM은 데이터를 제공하거나 DR(재해 복구)용으로 구성할 수 있습니다.
. 용량 기반 라이센스의 경우, 추가 스토리지 VM에 대한 추가 라이센스 비용이 없지만 스토리지 VM당 최소 용량 비용은 4TiB입니다. 예를 들어 스토리지 VM 2개를 생성하고 각 VM에 2TiB의 용량을 프로비저닝한 경우 총 8TiB가 충전됩니다.
. 노드 기반 BYOL의 경우, Cloud Volumes ONTAP에서 기본적으로 제공되는 첫 번째 스토리지 VM 외에 각 additional_data-serving_storage VM에 애드온 라이센스가 필요합니다. 스토리지 VM 애드온 라이센스를 얻으려면 어카운트 팀에 문의하십시오.
+
DR(재해 복구)에 대해 구성하는 스토리지 VM에는 추가 라이센스(무료)가 필요하지 않지만 스토리지 VM 제한에 대해 카운트됩니다. 예를 들어, 데이터 서비스 스토리지 VM 12개와 재해 복구용 스토리지 VM 12개가 구성되어 있는 경우, 한계에 도달하여 추가 스토리지 VM을 생성할 수 없습니다.





== 논리적 스토리지 제한입니다

[cols="22,22,56"]
|===
| 논리적 스토리지 | 매개 변수 | 제한 


.2+| * 파일 * | 최대 크기 | 16TB 


| 볼륨당 최대 | 볼륨 크기에 따라 다르며 최대 20억 개까지 가능합니다 


| FlexClone 볼륨 * | 계층적 복제 깊이 ^12^ | 499 


.3+| * FlexVol 볼륨 * | 노드당 최대 | 500입니다 


| 최소 크기 | 20MB 


| 최대 크기 | 100TB 


| * qtree * | FlexVol 볼륨당 최대 | 4,995 


| Snapshot 복사본 * | FlexVol 볼륨당 최대 | 1,023 
|===
. 계층적 클론 깊이는 단일 FlexVol 볼륨에서 생성할 수 있는 FlexClone 볼륨의 중첩 계층 구조의 최대 깊이입니다.




== iSCSI 스토리지 제한입니다

[cols="3*"]
|===
| iSCSI 스토리지 | 매개 변수 | 제한 


.4+| LUN * | 노드당 최대 | 1,024 


| 최대 LUN 매핑 수입니다 | 1,024 


| 최대 크기 | 16TB 


| 볼륨당 최대 | 512 


| Igroup * 을 선택합니다 | 노드당 최대 | 256 


.2+| * 이니시에이터 * | 노드당 최대 | 512 


| igroup당 최대 | 128 


| * iSCSI 세션 * | 노드당 최대 | 1,024 


.2+| LIF * | 포트당 최대 | 1 


| 최대 Per 포트셋 | 32 


| * 포트 세트 * | 노드당 최대 | 256 
|===