---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: 이러한 알려진 제한은 Amazon 웹 서비스의 Cloud Volumes ONTAP에만 적용됩니다. 
---
= AWS의 알려진 제한사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음은 Amazon Web Services의 Cloud Volumes ONTAP에만 적용되는 알려진 제한 사항입니다. 또한 반드시 검토하십시오 link:reference-limitations.html["모든 클라우드 공급자의 Cloud Volumes ONTAP 제한 사항"].



== AWS Outpost 제한 사항

AWS 아웃포스트가 있는 경우 작업 환경 마법사에서 아웃포스트 VPC를 선택하여 해당 아웃포스트에 Cloud Volumes ONTAP를 구축할 수 있습니다. 이러한 경험은 AWS에 상주하는 다른 VPC와 동일합니다. 먼저 AWS Outpost에 Connector를 구축해야 합니다.

몇 가지 제한 사항이 있습니다.

* 현재 단일 노드 Cloud Volumes ONTAP 시스템만 지원됩니다
* Cloud Volumes ONTAP와 함께 사용할 수 있는 EC2 인스턴스는 Outpost에서 사용할 수 있는 인스턴스로 제한됩니다
* 현재 GP2(범용 SSD)만 지원됩니다




== Flash Cache 제한

C5D 및 R5D 인스턴스 유형에는 Cloud Volumes ONTAP가 _Flash Cache_로 사용하는 로컬 NVMe 스토리지가 있습니다. 다음 제한 사항을 참고하십시오.

* Cloud Volumes ONTAP 9.12.0까지 Flash Cache 성능 향상을 활용하려면 모든 볼륨에서 압축을 해제해야 합니다. Cloud Volumes ONTAP 9.12.1을 배포하거나 업그레이드할 때 압축을 비활성화할 필요가 없습니다.
+
BlueXP에서 볼륨을 생성할 때 스토리지 효율성을 선택하지 않거나 볼륨을 생성한 후 생성할 수 있습니다 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["CLI를 사용하여 데이터 압축을 비활성화합니다"^].

* 재부팅 후 캐시 재가기는 Cloud Volumes ONTAP에서 지원되지 않습니다.




== Amazon CloudWatch에서 잘못된 경보가 보고되었습니다

Cloud Volumes ONTAP는 유휴 상태일 때는 CPU를 방출하지 않으므로 https://aws.amazon.com/cloudwatch/["Amazon CloudWatch 를 참조하십시오"^] 는 사용량이 100%로 표시되므로 EC2 인스턴스에 대해 높은 CPU 경고를 보고할 수 있습니다. 이 알람을 무시할 수 있습니다. ONTAP statistics 명령은 CPU의 실제 사용량을 표시합니다.



== Cloud Volumes ONTAP HA 쌍은 즉각적인 스토리지 반환을 지원하지 않습니다

노드가 재부팅된 후 파트너는 스토리지를 반환하기 전에 데이터를 동기화해야 합니다. 데이터를 재동기화하는 데 걸리는 시간은 노드가 다운된 동안 클라이언트가 쓴 데이터의 양과 반환 시간 동안 데이터 쓰기 속도에 따라 달라집니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["AWS에서 실행 중인 Cloud Volumes ONTAP HA 쌍에서 스토리지의 작동 방식에 대해 알아보십시오"^].
