---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: 이러한 알려진 제한은 Microsoft Azure의 Cloud Volumes ONTAP에만 적용됩니다. 
---
= Azure의 Cloud Volumes ONTAP에 대한 알려진 제한 사항입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Microsoft Azure의 Cloud Volumes ONTAP에는 다음과 같은 알려진 제한 사항이 있습니다. 또한 반드시 검토하십시오 link:reference-limitations.html["모든 클라우드 공급자의 Cloud Volumes ONTAP 제한 사항"].



== Azure VM 확장 사용 시 제한 사항

Cloud Volumes ONTAP Azure 가상 머신(VM) 확장을 지원하지 않습니다. VM 확장은 작업 지연을 유발하기 때문입니다. Cloud Volumes ONTAP 배포 후 BlueXP VM 확장을 주기적으로 비활성화합니다. 작업 환경에 이러한 확장을 설치한 경우 Microsoft Azure 지원팀에 문의하여 비활성화하거나 삭제하십시오.



== Flash Cache 제한

Cloud Volumes ONTAP은 일부 VM 유형에서 로컬 NVMe 스토리지를 _ Flash Cache _ 로 사용합니다. 이 제한 사항에 유의하십시오.

* 재부팅 후 캐시 다시 가기는 지원되지 않습니다.




== 고가용성 구축의 제한사항

일부 지역에서는 고가용성(HA) 쌍이 지원되지 않습니다.

https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 Azure 지역 목록을 봅니다"^]..



== 단일 가용 영역에서 HA 구축의 제한 사항

Cloud Volumes ONTAP 9.15.1부터 Azure의 AZ(단일 가용 영역)에 HA 모드로 가상 머신(VM) 인스턴스를 배포할 수 있습니다. 이 기능을 지원하는 기준에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Azure에서 단일 가용 영역에 HA 쌍을 구축합니다"^]참조하십시오.

Cloud Volumes ONTAP 버전이 9.15.1 이전 버전이거나 이러한 조건이 충족되지 않으면 가용성 집합을 사용하는 이전 배포 모델이 적용됩니다. 이 제한은 HA 구성에만 적용됩니다.
