---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.11.1에는 새로운 개선 사항이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.11.1의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.11.1에는 새로운 개선 사항이 포함되어 있습니다.

최신 버전의 Cloud Manager에는 추가 기능과 개선 사항도 포함되어 있습니다. 를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager 릴리즈 노트"^] 를 참조하십시오.



== 9.11.1 RC1(2022년 6월 7일)

Cloud Volumes ONTAP 9.11.1 릴리스 후보 1은 이제 AWS, Azure 및 Google 클라우드에서 사용할 수 있습니다. 이 릴리즈에는 다음과 같은 새로운 기능과 향상된 기능이 포함되어 있습니다.



=== 성능 향상

9.11.1 이상에서 생성된 새 애그리게이트의 읽기 성능이 향상되었습니다.



=== 스토리지 효율성 향상

9.11.1 릴리즈부터 스토리지 효율성을 위해 활성화된 모든 새로운 볼륨에 온도에 민감한 스토리지 효율성 이라는 새로운 압축 기능이 포함됩니다. 이전 세대 압축 기능은 더 이상 사용되지 않습니다.

온도에 민감한 스토리지 효율성 데이터 온도 또는 데이터 사용 빈도를 기준으로 데이터를 압축합니다. 자주 사용되지 않는 콜드 데이터 또는 데이터는 압축률이 더 높아 스토리지 효율성이 향상됩니다.



=== AWS에서 VPC 공유

Cloud Volumes ONTAP HA 쌍이 VPC 공유를 지원하는 AWS에서 이제 지원됩니다. VPC 공유를 사용하면 서브넷을 다른 AWS 계정과 공유할 수 있습니다. 네트워킹(VPC, 서브넷 및 라우트 테이블)은 VPC 소유자 계정에 상주하고 HA 구성의 EC2 인스턴스는 공유 서브넷을 사용하는 참가자 계정에 상주합니다.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploy-aws-shared-vpc.html["공유 서브넷에 HA 쌍을 구축하는 방법을 알아보십시오"^]



=== 새로운 AWS 지역 지원

Cloud Volumes ONTAP는 현재 AWS 자카르타 지역(AP-동남아시아-3)에서 지원됩니다.

https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes ONTAP에 대해 지원되는 전체 영역 목록을 봅니다"^]



=== 새로운 Azure 지역 지원

Cloud Volumes ONTAP는 현재 Azure 브라질 남동부 지역에서 지원됩니다.

https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes ONTAP에 대해 지원되는 전체 영역 목록을 봅니다"^]



=== Google Cloud에서 24개의 스토리지 VM 지원

현재 24개의 스토리지 VM이 Google Cloud의 Cloud Volumes ONTAP에서 대부분의 구성으로 지원됩니다.

* link:reference-limits-gcp.html#storage-vm-limits["Google Cloud의 스토리지 VM 제한에 대해 자세히 알아보십시오"]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html["Google Cloud에서 Cloud Volumes ONTAP용 데이터 서비스 스토리지 VM을 생성하는 방법을 알아보십시오"^]




=== 새로운 Google Cloud 지역 지원

Cloud Volumes ONTAP HA 쌍이 이제 밀라노(유럽-west8) 지역에서 지원됩니다.

https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes ONTAP에 대해 지원되는 전체 영역 목록을 봅니다"^]



=== 새 스토리지 VM에 대한 LIF 서비스 수정

이 릴리즈부터 AWS 또는 Azure의 Cloud Volumes ONTAP HA 쌍에서 새 스토리지 VM을 생성하는 경우, 스토리지 VM에 대한 네트워크 서비스 정책을 수정해야 합니다. Cloud Volumes ONTAP가 아웃바운드 관리 연결에 iSCSI LIF를 사용할 수 있도록 하기 때문에 서비스를 수정해야 합니다.

Cloud Manager API를 사용하면 생성 중에 LIF 서비스가 설정되므로 Google Cloud의 Cloud Volumes ONTAP에서는 LIF 서비스를 수정할 필요가 없습니다.

실행해야 하는 명령은 다음 페이지에서 지정합니다.

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-aws.html["AWS에서 추가 스토리지 VM을 생성하는 방법에 대해 알아보십시오"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html["Azure에서 추가 스토리지 VM을 생성하는 방법에 대해 알아보십시오"^]




== 지원되지 않는 새로운 ONTAP 기능입니다

ONTAP 9.11.1에 도입된 새로운 다중 관리 검증 기능은 Cloud Volumes ONTAP에서 지원되지 않습니다. Cloud Volumes ONTAP에서 다중 관리 검증을 활성화하면 지원되지 않는 구성이 발생합니다.



== 노트 업그레이드

이 릴리스 업그레이드에 대한 자세한 내용은 이 노트를 참조하십시오.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 Cloud Manager에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Cloud Manager에서 알림을 받을 때 업그레이드하는 방법에 대해 알아보십시오"^].



=== 지원되는 업그레이드 경로입니다

9.11.0 릴리스 및 9.10.1 릴리스에서 Cloud Volumes ONTAP 9.11.1로 업그레이드할 수 있습니다. Cloud Manager에서 해당 Cloud Volumes ONTAP 시스템을 이 릴리즈로 업그레이드하라는 메시지를 표시합니다.



=== 커넥터의 필수 버전입니다

새 Cloud Volumes ONTAP 9.11.1 시스템을 배포하고 기존 시스템을 9.11.1로 업그레이드하려면 Cloud Manager Connector가 버전 3.9.19 이상을 실행해야 합니다.


TIP: Connector의 자동 업그레이드는 기본적으로 활성화되어 있으므로 최신 버전을 실행해야 합니다.



=== 알아 보십시오

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.




=== C4, M4 및 R4 인스턴스 유형

9.8 릴리스, C4, M4 및 R4 인스턴스 유형부터 새로운 Cloud Volumes ONTAP 시스템에서는 지원되지 않습니다. C4, M4 또는 R4 인스턴스 유형에서 실행 중인 기존 Cloud Volumes ONTAP 시스템이 있는 경우에도 이 릴리즈로 업그레이드할 수 있습니다.

C5, M5 또는 R5 인스턴스 제품군의 인스턴스 유형으로 변경하는 것이 좋습니다.
