---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 모든 클라우드 공급자의 제한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.

AWS, Azure, Google Cloud와 같은 모든 클라우드 공급자의 Cloud Volumes ONTAP에는 다음과 같은 제한 사항이 적용됩니다.



== 최대 동시 복제 작업 수

인스턴스 유형 또는 시스템 유형에 상관없이 Cloud Volumes ONTAP에 대한 최대 동시 SnapMirror 또는 SnapVault 전송 수는 노드당 100개입니다.



== 클라우드 공급자 스냅샷은 백업 및 복구 계획에 사용할 수 없습니다

Cloud Volumes ONTAP 데이터에 대한 백업 및 복구 계획에 클라우드 공급자의 스냅샷을 사용하면 안 됩니다. 항상 ONTAP 스냅샷 복사본 또는 타사 백업 솔루션을 사용하여 Cloud Volumes ONTAP에 호스팅된 데이터를 백업 및 복원해야 합니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-backup-to-cloud.html["Cloud Backup Service를 사용하여 ONTAP 데이터를 백업 및 복원하는 방법에 대해 알아보십시오"^].


NOTE: WAFL 파일 시스템의 ONTAP 정합성 보장 지점에서 데이터 정합성 보장 확인 WAFL만 ONTAP 파일 시스템을 정지하여 충돌 시에도 정합성이 보장되는 백업을 수행할 수 있습니다.



== 중국 지역 지원

Cloud Volumes ONTAP는 중국 지역에서 다음과 같이 지원됩니다.

* Cloud Volumes ONTAP 9.6은 AWS 중국 지역에서 지원됩니다.
* 단일 노드 시스템이 지원됩니다.
* NetApp에서 직접 구매한 라이센스가 지원됩니다.


다른 모든 위치, 버전, 구성 및 라이센스는 지원되지 않습니다.



== Cloud Volumes ONTAP는 예약된 VM 인스턴스 및 주문형 VM 인스턴스를 지원합니다

Cloud Volumes ONTAP는 클라우드 공급자의 예약된 VM 인스턴스 또는 주문형 VM 인스턴스에서 실행될 수 있습니다. 다른 유형의 VM 인스턴스는 지원되지 않습니다.



== 자동 애플리케이션 리소스 관리 솔루션을 사용해서는 안 됩니다

자동 애플리케이션 리소스 관리 솔루션은 Cloud Volumes ONTAP 시스템을 관리해서는 안 됩니다. 이렇게 하면 지원되지 않는 구성이 변경될 수 있습니다. 예를 들어, 솔루션은 Cloud Volumes ONTAP를 지원되지 않는 VM 인스턴스 유형으로 변경할 수 있습니다.



== Cloud Manager에서 소프트웨어 업데이트를 완료해야 합니다

Cloud Volumes ONTAP 업그레이드는 Cloud Manager에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.



== Cloud Volumes ONTAP 배포는 클라우드 공급자의 콘솔에서 수정할 수 없습니다

클라우드 공급자의 콘솔에서 Cloud Volumes ONTAP 구성을 변경하면 지원되지 않는 구성이 발생합니다. Cloud Manager에서 생성 및 관리하는 Cloud Volumes ONTAP 리소스에 대한 모든 변경은 시스템 안정성과 Cloud Manager의 시스템 관리 기능에 영향을 줄 수 있습니다.



== 디스크와 애그리게이트는 Cloud Manager에서 관리해야 합니다

모든 디스크와 애그리게이트는 Cloud Manager에서 직접 생성 및 삭제해야 합니다. 다른 관리 도구에서 이러한 작업을 수행해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 주고 향후 디스크를 추가할 수 없도록 하며 중복 클라우드 공급자 비용을 생성할 수 있습니다.



== SnapManager 라이센스 제한

SnapManager 서버당 라이센스는 Cloud Volumes ONTAP에서 지원됩니다. 스토리지당 시스템(SnapManager 제품군) 라이센스는 지원되지 않습니다.



== 지원되지 않는 ONTAP 기능입니다

다음 기능은 Cloud Volumes ONTAP에서 지원되지 않습니다.

* 애그리게이트 레벨 인라인 중복제거
* 애그리게이트 레벨의 백그라운드 중복제거
* 디스크 유지보수 센터 를 참조하십시오
* 디스크 삭제
* FabricPool 미러링
* 파이버 채널(FC)
* Flash Pool을 참조하십시오
* 무한 확장 볼륨
* 인터페이스 그룹
* intranode LIF 페일오버
* MetroCluster
* Google Cloud의 ONTAP S3(S3 프로토콜이 Azure 및 AWS에서 지원됨)
* RAID4, RAID-DP, RAID-TEC(RAID0 지원)
* 서비스 프로세서
* SnapLock 규정 준수 및 엔터프라이즈 모드(클라우드 WORM만 지원)
* SnapMirror Synchronous
* VLAN

