---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP는 AWS에서 스토리지 구성을 제한하여 안정적인 운영 기능을 제공합니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오. 
---
= AWS의 Cloud Volumes ONTAP에 대한 스토리지 제한입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP는 안정적인 운영을 제공하기 위해 스토리지 구성에 제한이 있습니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오.



== 라이센스별 최대 시스템 용량

최대 시스템 용량에는 디스크 기반 스토리지와 데이터 계층화에 사용되는 개체 스토리지가 포함됩니다.

NetApp 시스템 용량 제한을 초과하는 것을 지원하지 않습니다. 라이센스된 용량 한도에 도달하면 NetApp 콘솔에 조치가 필요하다는 메시지가 표시되고 더 이상 추가 디스크를 추가할 수 없습니다.

일부 구성에서는 디스크 제한만으로 용량 제한에 도달하지 못합니다. 이 경우 를 통해 용량 제한에 도달할 수 있습니다 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. 자세한 내용은 아래의 용량 및 디스크 제한을 참조하십시오.

.용량 기반 라이선스에 대한 용량 제한
용량 기반 라이선싱을 통해 각 Cloud Volumes ONTAP 시스템은 개체 스토리지에 대한 계층화를 지원합니다.  전체 계층형 용량은 클라우드 제공자의 버킷 한도까지 확장될 수 있습니다.  라이센스에는 용량 제한이 부과되지 않지만 다음을 따라야 합니다. https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^] 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장합니다. 를 참조하세요  https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 문서"^] 자세한 내용은.

다른 라이센스 유형에 대한 용량 제한::


[cols="25,75"]
|===
| 라이센스 | 최대 시스템 용량(디스크 + 오브젝트 스토리지) 


| 프리모늄 | 500GiB 


| PAYGO 탐색 | 2TiB(데이터 계층화는 Explore에서 지원되지 않음) 


| PAYGO 표준 | 10TiB 


| PAYGO 프리미엄 | 368TiB 


| 노드 기반 라이센스 | PiB 2개(여러 개의 라이센스 필요) 
|===
.HA의 경우 노드당 또는 전체 HA 쌍의 라이센스 용량 제한이 있습니까?
용량 제한은 HA 쌍 전체에 적용됩니다.  노드당이 아닙니다.  예를 들어, 프리미엄 라이선스는 두 노드에서 최대 368TiB를 허용합니다.

.AWS의 HA 시스템에서 미러링된 데이터는 용량 제한에 따라 계산됩니까?
아니, 그렇지 않아요. AWS HA 쌍의 데이터는 장애 발생 시에도 데이터를 사용할 수 있도록 노드 간에 동기적으로 미러링됩니다. 예를 들어, 노드 A에서 8TiB 디스크를 구매하는 경우 콘솔은 미러링된 데이터에 사용되는 노드 B에도 8TiB 디스크를 할당합니다. 16TiB의 용량이 프로비저닝되었지만, 라이선스 한도에는 8TiB만 포함됩니다.



== 애그리게이트 제한

Cloud Volumes ONTAP는 EBS 볼륨을 디스크로 사용하고 이들을 _aggregate_로 그룹화합니다. Aggregate는 볼륨에 스토리지를 제공합니다.

[cols="2*"]
|===
| 매개 변수 | 제한 


| 최대 애그리게이트 수입니다 | 단일 노드: 디스크 한계 HA 쌍과 동일: 노드 ^1^에서 18 


| 최대 애그리게이트 크기 ^2^  a| 
* 96TiB의 물리적 용량
* Elastic Volumes^3^에 128TiB의 물리적 용량




| 애그리게이트당 디스크 ^4^  a| 
* 1-6
* 1-8 탄성 볼륨 ^3^




| 애그리게이트당 최대 RAID 그룹 수 | 1 
|===
참고:

. HA 쌍의 두 노드 모두에 18개의 집계를 만들 수 없습니다. 그렇게 하면 데이터 디스크 한도를 초과하게 됩니다.
. 최대 집계 크기는 디스크에 따라 달라지며 데이터 계층화에 사용하는 개체 스토리지는 포함되지 않습니다.
. Amazon EBS Elastic Volumes 기능을 지원하는 구성이 있는 경우 집계에는 최대 8개의 디스크가 포함될 수 있으며, 이는 최대 128TiB의 용량을 제공합니다.  기본적으로 Cloud Volumes ONTAP 9.11.0 이상 시스템에서는 gp3 또는 io1 디스크를 사용할 때 Amazon EBS Elastic Volumes가 활성화됩니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보십시오"^]
. Aggregate의 모든 디스크는 동일한 크기여야 합니다.




== EC2 인스턴스별로 디스크 및 계층화가 제한됩니다

용량 제한은 사용하는 EC2 인스턴스 유형 제품군과 단일 노드 시스템을 사용하는지 HA 쌍을 사용하는지에 따라 다릅니다.

다음 노트는 아래 표에 표시되는 숫자에 대한 세부 정보를 제공합니다.

* 디스크 제한은 사용자 데이터가 포함된 디스크에만 적용됩니다.
+
이 제한에는 부팅 디스크 및 루트 디스크가 포함되지 않습니다.

* 디스크를 단독으로 사용하거나 디스크 및 콜드 데이터 계층화를 오브젝트 스토리지에 사용할 경우 최대 시스템 용량이 표시됩니다.
* Cloud Volumes ONTAP는 EBS 볼륨을 디스크로 사용하며 최대 디스크 크기는 16TiB입니다.




=== 용량 기반 라이선싱의 다양한 배포 모드에 대한 제한

용량 기반 라이센스 패키지를 사용하는 Cloud Volumes ONTAP 시스템에는 다음과 같은 디스크 제한 사항이 적용됩니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이센스 옵션에 대해 자세히 알아보십시오"^]


NOTE: 단일 노드 및 HA 구성에 대한 최대 시스템 용량 및 데이터 계층화 용량 제한은 다음을 참조하세요.<<cap-license-aws>> .



==== 단일 노드

[cols="18,18,32,width=100%,options="]
|===


| 인스턴스 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 21 | 336TiB 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 19^1^ | 304TiB 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




==== HA 쌍

[cols="18,18,32,width=100%,options="]
|===


| 인스턴스 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 18 | TiB 288 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 16^1^ | 256TiB 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




=== 노드 기반 라이선싱의 다양한 배포 모드에 대한 제한 사항

노드별 Cloud Volumes ONTAP 라이센스를 설정할 수 있는 이전 세대 라이센스 모델인 노드 기반 라이센스를 사용하는 Cloud Volumes ONTAP 시스템에는 다음과 같은 디스크 제한이 적용됩니다. 기존 고객은 노드 기반 라이센스를 계속 사용할 수 있습니다.

Cloud Volumes ONTAP BYOL 단일 노드 또는 HA 쌍 시스템에 대해 노드 기반 라이센스를 여러 개 구매하여 최대 테스트 및 지원 시스템 용량 제한인 2개의 PiB까지 368TiB의 용량을 할당할 수 있습니다. 디스크 제한만으로는 용량 제한에 도달하지 못할 수 있습니다. 를 사용하면 디스크 제한을 초과할 수 있습니다 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP에 시스템 라이센스를 추가하는 방법에 대해 알아보십시오"^]. Cloud Volumes ONTAP는 최대 테스트 및 지원되는 시스템 용량인 2 PiB를 지원하지만 2 PiB 제한을 초과하면 지원되지 않는 시스템 구성이 발생합니다.

AWS Secret Cloud 및 Top Secret Cloud 지역에서는 Cloud Volumes ONTAP 9.12.1부터 다수의 노드 기반 라이센스 구매를 지원합니다.



==== PAYGO Premium이 포함된 단일 노드

[cols="18,18,32,32"]
|===
| 인스턴스 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 21^1^ | 336TiB | 368TiB 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 19^2^ | 304TiB | 368TiB 
|===
. 21개의 데이터 디스크는 Cloud Volumes ONTAP의 _new_deDeployments에 대한 제한입니다. 9.7 이하 버전으로 생성된 시스템을 업그레이드하면 시스템에서 22개의 디스크를 계속 지원합니다. 9.8 릴리즈부터 시작되는 코어 디스크가 추가되었기 때문에 이러한 인스턴스 유형을 사용하는 새 시스템에서는 데이터 디스크가 1개 적게 지원됩니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




==== BYOL, 단일 노드

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 | 노드당 최대 디스크 수입니다 2+| 하나의 라이센스로 최대 시스템 용량을 지원합니다 2+| 여러 라이센스가 있는 최대 시스템 용량 


2+|  | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * 


| C5, M5 및 R5 인스턴스 | 21^1^ | 336TiB | 368TiB | 336TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 19^2^ | 304TiB | 368TiB | 304TiB | 2 PiB 
|===
. 21개의 데이터 디스크는 Cloud Volumes ONTAP의 _new_deDeployments에 대한 제한입니다. 9.7 이하 버전으로 생성된 시스템을 업그레이드하면 시스템에서 22개의 디스크를 계속 지원합니다. 9.8 릴리즈부터 시작되는 코어 디스크가 추가되었기 때문에 이러한 인스턴스 유형을 사용하는 새 시스템에서는 데이터 디스크가 1개 적게 지원됩니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




==== PAYGO Premium과 HA 쌍

[cols="18,18,32,32"]
|===
| 인스턴스 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 18^1^ | TiB 288 | 368TiB 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 16^2^ | 256TiB | 368TiB 
|===
. Cloud Volumes ONTAP의 _new_de구축에는 18개의 데이터 디스크가 제한됩니다. 9.7 이전 버전으로 생성된 시스템을 업그레이드하면 시스템에서 계속 19개의 디스크를 지원합니다. 9.8 릴리즈부터 시작되는 코어 디스크가 추가되었기 때문에 이러한 인스턴스 유형을 사용하는 새 시스템에서는 데이터 디스크가 1개 적게 지원됩니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




==== BYOL의 HA 쌍

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 | 노드당 최대 디스크 수입니다 2+| 하나의 라이센스로 최대 시스템 용량을 지원합니다 2+| 여러 라이센스가 있는 최대 시스템 용량 


2+|  | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * 


| C5, M5 및 R5 인스턴스 | 18^1^ | TiB 288 | 368TiB | TiB 288 | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xLarge

| 16^2^ | 256TiB | 368TiB | 256TiB | 2 PiB 
|===
. Cloud Volumes ONTAP의 _new_de구축에는 18개의 데이터 디스크가 제한됩니다. 9.7 이전 버전으로 생성된 시스템을 업그레이드하면 시스템에서 계속 19개의 디스크를 지원합니다. 9.8 릴리즈부터 시작되는 코어 디스크가 추가되었기 때문에 이러한 인스턴스 유형을 사용하는 새 시스템에서는 데이터 디스크가 1개 적게 지원됩니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 더 많은 로컬 NVMe 디스크를 가지고 있으므로 더 적은 수의 데이터 디스크가 지원됩니다.




== 스토리지 VM 제한

일부 구성을 사용하면 Cloud Volumes ONTAP용 SVM(스토리지 VM)을 추가로 생성할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["추가 스토리지 VM을 생성하는 방법을 알아보십시오"^].

[cols="40,60"]
|===
| 사용권 유형 | 스토리지 VM 제한 


| * Freemium *  a| 
스토리지 VM 총 24개 ^1,2^



| * 용량 기반 PAYGO 또는 BYOL *^3^  a| 
스토리지 VM 총 24개 ^1,2^



| * 노드 기반 PAYGO *  a| 
* 1 데이터 제공용 스토리지 VM
* 재해 복구용 스토리지 VM 1개




| * 노드 기반 BYOL * ^4^  a| 
* 스토리지 VM 총 24개 ^1,2^


|===
. 사용하는 EC2 인스턴스 유형에 따라 이 제한을 줄일 수 있습니다. 인스턴스당 제한은 아래 섹션에 나와 있습니다.
. 이러한 24개의 스토리지 VM은 데이터를 제공하거나 DR(재해 복구)용으로 구성할 수 있습니다.
. 용량 기반 라이센스의 경우, 추가 스토리지 VM에 대한 추가 라이센스 비용이 없지만 스토리지 VM당 최소 용량 비용은 4TiB입니다. 예를 들어 스토리지 VM 2개를 생성하고 각 VM에 2TiB의 용량을 프로비저닝한 경우 총 8TiB가 충전됩니다.
. 노드 기반 BYOL의 경우, Cloud Volumes ONTAP에서 기본적으로 제공되는 첫 번째 스토리지 VM 외에 각 additional_data-serving_storage VM에 애드온 라이센스가 필요합니다. 스토리지 VM 애드온 라이센스를 얻으려면 어카운트 팀에 문의하십시오.
+
DR(재해 복구)에 대해 구성하는 스토리지 VM에는 추가 라이센스(무료)가 필요하지 않지만 스토리지 VM 제한에 대해 카운트됩니다. 예를 들어, 데이터 서비스 스토리지 VM 12개와 재해 복구용 스토리지 VM 12개가 구성되어 있는 경우, 한계에 도달하여 추가 스토리지 VM을 생성할 수 없습니다.





=== EC2 인스턴스 유형별 스토리지 VM 제한

추가 스토리지 VM을 생성할 때 e0a 포트에 전용 IP 주소를 할당해야 합니다. 아래 표에는 Cloud Volumes ONTAP 구축 후 포트 e0a에서 사용 가능한 IP 주소 수와 인터페이스당 프라이빗 IP의 최대 수가 나와 있습니다. 사용 가능한 IP 주소 수는 해당 구성에 대한 최대 스토리지 VM 수에 직접 영향을 줍니다.

아래 나열된 인스턴스는 C5, M5 및 R5 인스턴스 제품군에 대한 것입니다.

[cols="6*"]
|===
| 구성 | 인스턴스 유형 | 인터페이스당 최대 사설 IP | 구축 후 IPS 잔여 ^1^ | 관리 LIF가 없는 최대 스토리지 VM ^2,3^ | 관리 LIF가 ^2,3^인 최대 스토리지 VM 


.9+| * 단일 노드 * | *.xLarge | 15 | 9 | 10 | 5 


| *.2xLarge | 15 | 9 | 10 | 5 


| *.4xLarge | 30 | 24 | 24 | 12 


| *.8xLarge | 30 | 24 | 24 | 12 


| *.9xLarge | 30 | 24 | 24 | 12 


| *.12xLarge | 30 | 24 | 24 | 12 


| *.16xLarge | 50 | 44 | 24 | 12 


| *.18xLarge | 50 | 44 | 24 | 12 


| *.24xLarge | 50 | 44 | 24 | 12 


.9+| 단일 AZ * 의 HA 쌍 | *.xLarge | 15 | 10 | 11 | 5 


| *.2xLarge | 15 | 10 | 11 | 5 


| *.4xLarge | 30 | 25 | 24 | 12 


| *.8xLarge | 30 | 25 | 24 | 12 


| *.9xLarge | 30 | 25 | 24 | 12 


| *.12xLarge | 30 | 25 | 24 | 12 


| *.16xLarge | 50 | 45 | 24 | 12 


| *.18xLarge | 50 | 45 | 24 | 12 


| *.24xLarge | 50 | 44 | 24 | 12 


.9+| * 멀티 AZs * 의 HA 쌍 | *.xLarge | 15 | 12 | 13 | 13 


| *.2xLarge | 15 | 12 | 13 | 13 


| *.4xLarge | 30 | 27 | 24 | 24 


| *.8xLarge | 30 | 27 | 24 | 24 


| *.9xLarge | 30 | 27 | 24 | 24 


| *.12xLarge | 30 | 27 | 24 | 24 


| *.16xLarge | 50 | 47 | 24 | 24 


| *.18xLarge | 50 | 47 | 24 | 24 


| *.24xLarge | 50 | 44 | 24 | 12 
|===
. 이 숫자는 Cloud Volumes ONTAP를 구축하고 설정한 후 포트 e0a에서 사용 가능한 _remaining_private IP 주소 수를 나타냅니다. 예를 들어, *.2xLarge 시스템은 네트워크 인터페이스당 최대 15개의 IP 주소를 지원합니다. HA 쌍이 단일 AZ에 배포되면 5개의 전용 IP 주소가 e0a 포트에 할당됩니다. 따라서 *.2xLarge 인스턴스 유형을 사용하는 HA 쌍에는 추가 스토리지 VM에 사용할 수 있는 10개의 전용 IP 주소가 남아 있습니다.
. 이 열에 나열된 숫자에는 콘솔이 기본적으로 생성하는 초기 스토리지 VM이 포함됩니다. 예를 들어, 이 열에 24가 나열되어 있다면 총 24개까지 추가 스토리지 VM을 만들 수 있다는 의미입니다.
. 스토리지 VM의 관리 LIF는 선택 사항입니다. 관리 LIF는 SnapCenter과 같은 관리 툴에 대한 연결을 제공합니다.
+
이 경우 전용 IP 주소가 필요하므로 생성할 수 있는 추가 스토리지 VM의 수가 제한됩니다. 단, 여러 AZs의 HA 쌍만 예외입니다. 이 경우 관리 LIF의 IP 주소는 _floating_ip 주소이므로 _private_ip 제한에 대해 계산되지 않습니다.





== 파일 및 볼륨 제한

[cols="22,22,56"]
|===
| 논리적 스토리지 | 매개 변수 | 제한 


.2+| * 파일 * | 최대 크기 2 | 128TB 


| 볼륨당 최대 | 볼륨 크기에 따라 다르며 최대 20억 개까지 가능합니다 


| FlexClone 볼륨 * | 계층적 복제 깊이 ^1^ | 499 


.3+| * FlexVol 볼륨 * | 노드당 최대 | 500입니다 


| 최소 크기 | 20MB 


| 최대 크기 3 | 300TiB 


| * qtree * | FlexVol 볼륨당 최대 | 4,995 


| Snapshot 복사본 * | FlexVol 볼륨당 최대 | 1,023 
|===
. 계층적 클론 깊이는 단일 FlexVol 볼륨에서 생성할 수 있는 FlexClone 볼륨의 중첩 계층 구조의 최대 깊이입니다.
. ONTAP 9.12.1P2부터 128TB가 제한됩니다. ONTAP 9.11.1 이하 버전에서는 16TB로 제한됩니다.
. 최대 300TiB의 FlexVol 볼륨 생성은 다음 툴 및 최소 버전을 사용할 수 있습니다.
+
** Cloud Volumes ONTAP 9.12.1 P2 및 9.13.0 P2부터 시작하는 System Manager 및 ONTAP CLI
** Cloud Volumes ONTAP 9.13.1부터 시작






== iSCSI 스토리지 제한입니다

[cols="3*"]
|===
| iSCSI 스토리지 | 매개 변수 | 제한 


.4+| LUN * | 노드당 최대 | 1,024 


| 최대 LUN 매핑 수입니다 | 1,024 


| 최대 크기 | 16TiB 


| 볼륨당 최대 | 512 


| Igroup * 을 선택합니다 | 노드당 최대 | 256 


.2+| * 이니시에이터 * | 노드당 최대 | 512 


| igroup당 최대 | 128 


| * iSCSI 세션 * | 노드당 최대 | 1,024 


.2+| LIF * | 포트당 최대 | 32 


| 최대 Per 포트셋 | 32 


| * 포트 세트 * | 노드당 최대 | 256 
|===